on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@66c73c18538167a69c9a7b658015bec113e7692d # v3.4.4
